import fs from "fs/promises";
import { createWriteStream } from "fs";
import path from "path";
import PDFDocument from "pdfkit";

// ── Configuration ──────────────────────────────────────────────────────────
const CONFIG = {
  pageSize: "A4",
  margins: { top: 60, bottom: 60, left: 55, right: 55 },

  // Body text
  bodyFont: "Helvetica",
  bodySize: 11,
  lineGap: 4,

  // Headings (detected from structural markers)
  h1Font: "Helvetica-Bold",
  h1Size: 20,
  h2Font: "Helvetica-Bold",
  h2Size: 16,
  h3Font: "Helvetica-Bold",
  h3Size: 13,

  // Page numbers
  showPageNumbers: true,
  pageNumberSize: 9,

  // Header (optional title on each page)
  showHeader: false,
  headerSize: 8,
};

// ── Detect line type from structural markers ───────────────────────────────
// These match the markers generated by to-text.js
function classifyLine(line, nextLine, prevLine) {
  // H1: line between ============= markers
  if (/^={10,}$/.test(prevLine) && /^={10,}$/.test(nextLine)) {
    return { type: "h1", text: line.trim() };
  }

  // H2: line between ------------- markers
  if (/^-{10,}$/.test(prevLine) && /^-{10,}$/.test(nextLine)) {
    return { type: "h2", text: line.trim() };
  }

  // H3: starts with ###
  if (/^###\s+/.test(line)) {
    return { type: "h3", text: line.replace(/^###\s+/, "").trim() };
  }

  // Separator line (═══, ───, ---, === )
  if (/^[=─\-]{10,}$/.test(line)) {
    return { type: "separator", text: "" };
  }

  // Bullet list item
  if (/^\s*[•·▪▸►-]\s+/.test(line)) {
    return { type: "bullet", text: line.replace(/^\s*[•·▪▸►-]\s+/, "").trim() };
  }

  // Image placeholder
  if (/^\[Image.*\]$/.test(line.trim())) {
    return { type: "image-placeholder", text: line.trim() };
  }

  // Empty line
  if (line.trim() === "") {
    return { type: "empty", text: "" };
  }

  // Regular paragraph text
  return { type: "body", text: line };
}

// ── Main conversion ────────────────────────────────────────────────────────
async function convertTxtToPdf(inputPath, outputPath, options = {}) {
  const cfg = { ...CONFIG, ...options };

  console.log(`📄 Reading: ${inputPath}`);
  const text = await fs.readFile(inputPath, "utf-8");
  const lines = text.split("\n");
  const inputSizeKb = (Buffer.byteLength(text) / 1024).toFixed(0);
  console.log(`   Size: ${inputSizeKb} KB | Lines: ${lines.length.toLocaleString()}`);

  // Try to extract title from first meaningful lines
  let docTitle = path.basename(inputPath, path.extname(inputPath));
  for (let i = 0; i < Math.min(10, lines.length); i++) {
    const l = lines[i].trim();
    if (l && !/^[=\-─#\s]*$/.test(l)) {
      docTitle = l.substring(0, 100);
      break;
    }
  }

  console.log(`\n📝 Generating PDF...`);

  const doc = new PDFDocument({
    size: cfg.pageSize,
    margins: cfg.margins,
    info: {
      Title: docTitle,
      Creator: "epub-converter txt-to-pdf",
      CreationDate: new Date(),
    },
    bufferPages: true,
    autoFirstPage: true,
    compress: true,
  });

  const outStream = createWriteStream(outputPath);
  doc.pipe(outStream);

  let pageCount = 1;
  let lastProgressPct = 0;

  // Track page count via event (no writing inside handler)
  doc.on("pageAdded", () => {
    pageCount++;
  });

  // Process lines
  let consecutiveEmpty = 0;

  for (let i = 0; i < lines.length; i++) {
    const prevLine = i > 0 ? lines[i - 1] : "";
    const nextLine = i < lines.length - 1 ? lines[i + 1] : "";
    const { type, text: content } = classifyLine(lines[i], nextLine, prevLine);

    // Progress
    const pct = Math.floor((i / lines.length) * 100);
    if (pct > lastProgressPct) {
      lastProgressPct = pct;
      if (pct % 5 === 0) {
        process.stdout.write(`\r   [${pct}%] Line ${i.toLocaleString()}/${lines.length.toLocaleString()} | Pages: ${pageCount}    `);
      }
    }

    switch (type) {
      case "h1":
        consecutiveEmpty = 0;
        ensureSpace(doc, 80, cfg);
        doc.moveDown(0.8);
        doc.font(cfg.h1Font).fontSize(cfg.h1Size);
        doc.text(content, { align: "center" });
        doc.moveDown(0.5);
        break;

      case "h2":
        consecutiveEmpty = 0;
        ensureSpace(doc, 60, cfg);
        doc.moveDown(0.6);
        doc.font(cfg.h2Font).fontSize(cfg.h2Size);
        doc.text(content);
        doc.moveDown(0.3);
        break;

      case "h3":
        consecutiveEmpty = 0;
        ensureSpace(doc, 50, cfg);
        doc.moveDown(0.4);
        doc.font(cfg.h3Font).fontSize(cfg.h3Size);
        doc.text(content);
        doc.moveDown(0.2);
        break;

      case "separator":
        // Don't render separator lines (they're heading markers), just skip
        break;

      case "bullet":
        consecutiveEmpty = 0;
        doc.font(cfg.bodyFont).fontSize(cfg.bodySize);
        doc.text(`  \u2022  ${content}`, {
          indent: 15,
          lineGap: cfg.lineGap,
        });
        break;

      case "image-placeholder":
        consecutiveEmpty = 0;
        doc.font("Helvetica-Oblique").fontSize(cfg.bodySize - 1);
        doc.fillColor("#888888").text(content, { align: "center" });
        doc.fillColor("#000000");
        break;

      case "empty":
        consecutiveEmpty++;
        // Max 2 consecutive empty lines in PDF
        if (consecutiveEmpty <= 2) {
          doc.moveDown(0.4);
        }
        break;

      case "body":
      default:
        consecutiveEmpty = 0;
        doc.font(cfg.bodyFont).fontSize(cfg.bodySize);
        doc.text(content, {
          lineGap: cfg.lineGap,
          align: "left",
        });
        break;
    }
  }

  // Add page numbers to all pages using buffered pages
  if (cfg.showPageNumbers) {
    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i++) {
      doc.switchToPage(i);
      const pageNum = i + 1;
      doc
        .font("Helvetica")
        .fontSize(cfg.pageNumberSize)
        .fillColor("#999999");
      const bottomY = doc.page.height - cfg.margins.bottom + 20;
      const pageWidth = doc.page.width;
      doc.text(`— ${pageNum} —`, 0, bottomY, {
        width: pageWidth,
        align: "center",
      });
      doc.fillColor("#000000");
    }
  }

  doc.end();
  await new Promise((resolve) => outStream.on("finish", resolve));

  const outputStats = await fs.stat(outputPath);
  const sizeMb = (outputStats.size / 1024 / 1024).toFixed(2);

  console.log(`\n\n✅ Done! Output: ${outputPath}`);
  console.log(`   Size: ${sizeMb} MB`);
  console.log(`   Pages: ${pageCount}`);
}

function ensureSpace(doc, neededPt, cfg) {
  const pageHeight =
    doc.page.height - cfg.margins.top - cfg.margins.bottom;
  const remaining = pageHeight - (doc.y - cfg.margins.top);
  if (remaining < neededPt) {
    doc.addPage();
  }
}

// ── CLI ────────────────────────────────────────────────────────────────────
const args = process.argv.slice(2);

if (args.length < 1 || args.includes("--help")) {
  console.log(`
╔══════════════════════════════════════════════════════════╗
║              TXT → PDF Converter                         ║
║  Converts plain text files to formatted PDF with         ║
║  headings, bullets, page numbers, and structure.         ║
╚══════════════════════════════════════════════════════════╝

Usage:
  node txt-to-pdf.js <input.txt> [output.pdf] [options]

Options:
  --font-size <n>     Body font size (default: 11)
  --page <size>       Page size: A4, LETTER, LEGAL (default: A4)
  --no-page-numbers   Disable page numbers

Examples:
  node txt-to-pdf.js book.txt
  node txt-to-pdf.js book.txt book.pdf
  node txt-to-pdf.js book.txt --font-size 12 --page LETTER
`);
  process.exit(0);
}

// Parse arguments
let inputFile = null;
let outputFile = null;
const options = {};

for (let i = 0; i < args.length; i++) {
  if (args[i] === "--font-size" && args[i + 1]) {
    options.bodySize = parseInt(args[++i], 10);
  } else if (args[i] === "--page" && args[i + 1]) {
    options.pageSize = args[++i].toUpperCase();
  } else if (args[i] === "--no-page-numbers") {
    options.showPageNumbers = false;
  } else if (!inputFile) {
    inputFile = path.resolve(args[i]);
  } else if (!outputFile) {
    outputFile = path.resolve(args[i]);
  }
}

if (!outputFile) {
  outputFile = inputFile.replace(/\.txt$/i, ".pdf");
  if (outputFile === inputFile) outputFile = inputFile + ".pdf";
}

try {
  await fs.access(inputFile);
} catch {
  console.error(`❌ File not found: ${inputFile}`);
  process.exit(1);
}

const startTime = Date.now();
await convertTxtToPdf(inputFile, outputFile, options);
const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
console.log(`   Time: ${elapsed}s`);
